### ISSUE TITLE
Core dump when string entered

### ISSUE THREAD

**Issue by jogo9225** [soniaszeton/CSCI2270_FinalProject#5]
When I enter a string for "Which will you choose?," I get a core dump:
"Which will you choose?
1. Bulbasaur
2. Charmander
3. Squirtle
joel
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
Aborted (core dumped)"

**Comment by soniaszeton** [comment]
That's why the compiler needs to be c++11 or higher so it will recognize the stoi argument. The compiller requirements are in the ReadMe
